# Enable H2 web console (accessible at localhost:8080/console)
spring.h2.console.enabled=true

# Path to access the H2 console in browser
spring.h2.console.path=/console

# Database name ? always generates with this name
spring.datasource.url=jdbc:h2:mem:testdb

# Show SQL queries in console (useful for debugging)
logging.level.org.hibernate.SQL=DEBUG